# Generated by Django 4.2.7 on 2025-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoglog',
            name='ai_response',
            field=models.TextField(default='', verbose_name='Ответ ИИ'),
        ),
        migrations.AddField(
            model_name='dialoglog',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='dialoglog',
            name='session_id',
            field=models.CharField(default='unknown', max_length=100, verbose_name='ID сессии'),
        ),
        migrations.AddField(
            model_name='dialoglog',
            name='specialist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специалист'),
        ),
        migrations.AddField(
            model_name='dialoglog',
            name='user_message',
            field=models.TextField(default='', verbose_name='Сообщение пользователя'),
        ),
        migrations.AlterField(
            model_name='dialoglog',
            name='channel',
            field=models.CharField(choices=[('voice', 'Голосовой звонок'), ('web', 'Веб-сайт'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='web', max_length=20, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='dialoglog',
            name='intent',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Намерение'),
        ),
        migrations.AlterField(
            model_name='dialoglog',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ системы'),
        ),
        migrations.AlterField(
            model_name='dialoglog',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Транскрипт диалога'),
        ),
    ]
