# Generated by Django 4.2.7 on 2025-09-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dialoglog_ai_response_dialoglog_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoglog',
            name='applied_playbooks',
            field=models.JSONField(blank=True, default=list, verbose_name='Применённые плейбуки'),
        ),
    ]
