# Generated by Django 4.2.7 on 2025-10-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dialoglog_applied_playbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialoglog',
            name='channel',
            field=models.CharField(choices=[('voice', 'Голосовой звонок'), ('web', 'Веб-сайт'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('vk', 'VKontakte'), ('sms', 'SMS')], default='web', max_length=20, verbose_name='Канал'),
        ),
    ]
