# Generated by Django 4.2.7 on 2025-10-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dialoglog_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialoglog',
            name='channel',
            field=models.CharField(choices=[('web', 'Веб-сайт')], default='web', max_length=20, verbose_name='Канал'),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
