# Generated by Django 4.2.7 on 2025-10-20 18:52

from django.db import migrations


def update_vip_price(apps, schema_editor):
    """Обновляем цену VIP диагностики с 550₪ на 5500₪"""
    Service = apps.get_model('core', 'Service')
    try:
        vip_service = Service.objects.get(name__icontains='VIP')
        vip_service.price = 5500
        vip_service.save()
        print(f"Цена VIP услуги обновлена на {vip_service.price}₪")
    except Service.DoesNotExist:
        print("VIP услуга не найдена")


def reverse_vip_price(apps, schema_editor):
    """Возврат к старой цене (если понадобится откат)"""
    Service = apps.get_model('core', 'Service')
    try:
        vip_service = Service.objects.get(name__icontains='VIP')
        vip_service.price = 550
        vip_service.save()
    except Service.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage'),
    ]

    operations = [
        migrations.RunPython(update_vip_price, reverse_vip_price),
    ]
