# Generated by Django 4.2.7 on 2025-10-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20251020_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('-24h', 'За 24 часа'), ('-2h', 'За 2 часа')], max_length=10, verbose_name='Тип напоминания')),
                ('scheduled_at', models.DateTimeField(verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['appointment', 'reminder_type'], name='core_remind_appoint_988d21_idx'), models.Index(fields=['status', 'scheduled_at'], name='core_remind_status_6f3be2_idx')],
            },
        ),
    ]
